server:
  port: 8002
#注册中心
eureka:
  # 关闭自我保护 ,暂停的关闭的服务可以被剔除
  server:
    enable-self-preservation: false  
  instance:
    hostname: mate2
    #prefer-ip-address: true
  client:
    #不将自身注册到服务器 - > false
    register-with-eureka: true
    #不需要检索服务 ->false
    fetch-registry: true
    service-url:
    #声明注册中心的地址和端口
      defaultZone: http://mate1:8001/eureka/
    healthcheck:
       enabled: true