server:
  port: 8001
#注册中心
eureka:
  instance:
    hostname: mate1
    #prefer-ip-address: true
  client:
    #不将自身注册到服务器 - > false
    register-with-eureka: true
    #不需要检索服务 ->false
    fetch-registry: true
    service-url:
    #声明注册中心的地址和端口
      defaultZone: http://mate2:8002/eureka/
    healthcheck:
       enabled: true