server:
  port: 8082

# 注册到注册中心的服务，不再通过地址访问，而是服务名  
spring:
  application:
    name: provider
  rabbitmq:
    host: localhost
    port: 15672
    username: test
    password: 123456

#注册中心
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaulutZone: http://${eureka.instance.hostname}:8761/eureka/
