#server:
  #port: 8082

#默认激活哪一个环境的配置文件
spring:
  profiles:
    active: dev
  #公共配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
---     
spring:
  profiles: dev 
  application:
     name: dev-port    
---  
spring:
  profiles: test 
  application:
     name: test-port   
---          

# 注册到注册中心的服务，不再通过地址访问，而是服务名  
spring:
  application:
    name: provider
  rabbitmq:
    host: localhost
    port: 15672
    username: test
    password: 123456

#注册中心
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaulutZone: http://master:8761/eureka/,http://slaver:8762/eureka/
      #defaulutZone: http://${spring.application.name}:8761/eureka/
