spring:
  application:
    name: muses-gateway

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      #defaulutZone: http://${eureka.instance.hostname}:8761/eureka/
      defaultZone: http://mate1:8001/eureka/,http://mate2:8002/eureka/
   # availability-zones:
      

zuul:
  routes:
    sale:
      #path: /sale/**
      path: /**
      # 路由的服务器Id
      service-id: invoker     
#zuul:
 # routes:
    # Map
    # this is key
  #  books:
      #the value
   #   url: http://localhost:8090