server:
  port: 8762

spring:
  application:
    name: eureka
    
#注册中心
eureka:
  instance:
    hostname: slaver
    prefer-ip-address: true
  client:
  #不将自身注册到服务器
    register-with-eureka: false
    fetch-registry: false
    service-url:
    #声明注册中心的地址和端口
      defaulutZone: http://master:8762/eureka/
