spring:
  application:
    name: eureka

server:
  port: 8002

    
#注册中心
eureka:
  instance:
    hostname: slaver
    #prefer-ip-address: true
  client:
    #不将自身注册到服务器 - > false
    register-with-eureka: true
    #不需要检索服务 ->false
    fetch-registry: true
    service-url:
    #声明注册中心的地址和端口
      defaulutZone: http://master:8001/eureka/
