server:
  port: 8001

spring:
  application:
    name: eureka
    
#注册中心
eureka:
  instance:
    hostname: master
    #prefer-ip-address: true
  client:
    #不将自身注册到服务器 - > false
    register-with-eureka: true
    #不需要检索服务 ->false
    fetch-registry: true
    service-url:
    #声明注册中心的地址和端口
      defaulutZone: http://slaver:8002/eureka/
