server:
  port: 8761

spring:
  application:
    name: eureka
    
#注册中心
eureka:
  instance:
    hostname: master
    prefer-ip-address: true
  client:
    #不将自身注册到服务器
    register-with-eureka: false 
    #不需要检索服务
    fetch-registry: false
    service-url:
    #声明注册中心的地址和端口
      #defaulutZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaulutZone: http://slaver:8762/eureka/
